name: CI/CD Pipeline for komawatsir

on:
  push:
    branches:
      - main

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
      # 1. 코드 체크아웃
      - name: Checkout code
        uses: actions/checkout@v3

      # 2. JDK 설치
      - name: Set up JDK
        uses: actions/setup-java@v3
        with:
          java-version: '17'
          distribution: 'temurin'

      # 3. Gradle 빌드
      - name: Build with Gradle
        run: ./gradlew clean build -x test

      # 4. AWS 자격 증명 설정
      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v2
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ap-northeast-2

      # 5. Amazon ECR 로그인
      - name: Log in to Amazon ECR
        id: login-ecr
        uses: aws-actions/amazon-ecr-login@v1

      # 6. Docker 이미지 빌드 및 푸시
      - name: Build, Tag, and Push Docker image
        env:
          ECR_REPOSITORY: aendyear-back
        run: |
          IMAGE_TAG=latest
          IMAGE_URI="${{ steps.login-ecr.outputs.registry }}/$ECR_REPOSITORY:$IMAGE_TAG"
          docker build -t $ECR_REPOSITORY:$IMAGE_TAG .
          docker tag $ECR_REPOSITORY:$IMAGE_TAG $IMAGE_URI
          docker push $IMAGE_URI

      # 7. 새 Task Definition 등록
      - name: Register new Task Definition
        env:
          AWS_REGION: ap-northeast-2
          IMAGE_URI: ${{ steps.login-ecr.outputs.registry }}/aendyear-back:${{ env.IMAGE_TAG }}
        run: |
          # 기존 Task Definition을 가져옴
          aws ecs describe-task-definition \
            --task-definition AendyearTask \
            --region $AWS_REGION > task-definition.json

          # 새 이미지 URI를 Task Definition에 반영
          jq '.taskDefinition.containerDefinitions[0].image = env.IMAGE_URI | .taskDefinition' task-definition.json \
            | jq 'del(.taskDefinitionArn, .revision, .status, .requiresAttributes, .compatibilities, .registeredAt, .registeredBy)' > new-task-definition.json

          # 새 Task Definition 등록 후 revision 번호 추출
          TASK_DEFINITION_REVISION=$(aws ecs register-task-definition \
            --cli-input-json file://new-task-definition.json \
            --region $AWS_REGION \
            --query 'taskDefinition.revision' --output text)

          echo "New Task Definition revision: $TASK_DEFINITION_REVISION"
          
          # revision 값이 제대로 출력되는지 확인하기 위해 로그 출력
          echo "TASK_DEFINITION_REVISION: $TASK_DEFINITION_REVISION"

      # 8. ECS 서비스 업데이트
      - name: Update ECS Service
        env:
          AWS_REGION: ap-northeast-2
        run: |
          # 새 revision을 사용하여 ECS 서비스 업데이트
          if [[ -z "$TASK_DEFINITION_REVISION" ]]; then
            echo "Error: Revision number not found!"
            exit 1
          fi

          # ECS 서비스 업데이트
          aws ecs update-service \
            --cluster AendyearCluster \
            --service komawotsir-aendyear \
            --task-definition AendyearTask:$TASK_DEFINITION_REVISION \
            --region $AWS_REGION \
            --force-new-deployment
