name: CI/CD Pipeline for komawatsir

on:
  push:
    branches:
      - main

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
      # 1. 코드 체크아웃
      - name: Checkout code
        uses: actions/checkout@v3

      # 2. JDK 설치
      - name: Set up JDK
        uses: actions/setup-java@v3
        with:
          java-version: '17'
          distribution: 'temurin'

      # 3. Gradle 빌드
      - name: Build with Gradle
        run: ./gradlew clean build -x test

      # 4. AWS 자격 증명 설정
      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v2
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ap-northeast-2

      # 5. Amazon ECR 로그인
      - name: Log in to Amazon ECR
        id: login-ecr
        uses: aws-actions/amazon-ecr-login@v1

      # 6. Docker 이미지 빌드 및 푸시
      - name: Build, Tag, and Push Docker image
        env:
          ECR_REPOSITORY: aendyear-back
        run: |
          IMAGE_TAG=latest
          IMAGE_URI="${{ steps.login-ecr.outputs.registry }}/$ECR_REPOSITORY:$IMAGE_TAG"
          docker build --no-cache -t $ECR_REPOSITORY:$IMAGE_TAG .
          docker tag $ECR_REPOSITORY:$IMAGE_TAG $IMAGE_URI
          docker push $IMAGE_URI

      # 7. Task Definition을 새로운 이미지로 업데이트
      - name: Update Task Definition with new image
        env:
          AWS_REGION: ap-northeast-2
          IMAGE_URI: ${{ steps.login-ecr.outputs.registry }}/aendyear-back:latest
        run: |
          # 기존 Task Definition을 가져옴
          aws ecs describe-task-definition \
            --task-definition AendyearTask \
            --region $AWS_REGION > task-definition.json

          # 새로운 이미지 URI를 Task Definition에 반영
          jq '.taskDefinition.containerDefinitions[0].image = env.IMAGE_URI | .taskDefinition' task-definition.json \
            | jq 'del(.taskDefinitionArn, .revision, .status, .requiresAttributes, .compatibilities, .registeredAt, .registeredBy)' > new-task-definition.json

          # 새로운 Task Definition 등록
          aws ecs register-task-definition \
            --cli-input-json file://new-task-definition.json \
            --region $AWS_REGION

      # 8. Target Group 상태 확인 후 ECS 서비스 업데이트
      - name: Wait for ECS tasks to be healthy
        env:
          AWS_REGION: ap-northeast-2
          CLUSTER_NAME: ${{ secrets.ECS_CLUSTER_NAME }}
          SERVICE_NAME: ${{ secrets.ECS_SERVICE_NAME }}
        run: |
      # ECS 서비스 업데이트 진행
          echo "ECS 서비스 업데이트 시작..."
          aws ecs update-service \
            --cluster $CLUSTER_NAME \
            --service $SERVICE_NAME \
            --task-definition AendyearTask \
            --region $AWS_REGION
               
          echo "ECS 서비스 안정화 대기 중..."
          aws ecs wait services-stable \
            --cluster $CLUSTER_NAME \
            --services $SERVICE_NAME \
            --region $AWS_REGION || { echo "ECS 서비스 안정화 실패"; exit 1; }
          echo "ECS 서비스 업데이트 완료."