name: CI/CD Pipeline for komawatsir

on:
  push:
    branches:
      - main

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
      # 1. 코드 체크아웃
      - name: Checkout code
        uses: actions/checkout@v3

      # 2. JDK 설치
      - name: Set up JDK
        uses: actions/setup-java@v3
        with:
          java-version: '17'
          distribution: 'temurin'

      # 3. Gradle 빌드
      - name: Build with Gradle
        run: ./gradlew clean build -x test

      # 4. AWS 자격 증명 설정
      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v2
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ap-northeast-2

      # 5. Amazon ECR 로그인
      - name: Log in to Amazon ECR
        id: login-ecr
        uses: aws-actions/amazon-ecr-login@v1

      # 6. Docker 이미지 빌드 및 푸시
      - name: Build, Tag, and Push Docker image
        env:
          ECR_REPOSITORY: aendyear-back
        run: |
          IMAGE_TAG=$(git rev-parse --short HEAD)
          IMAGE_URI="${{ steps.login-ecr.outputs.registry }}/$ECR_REPOSITORY:$IMAGE_TAG"
          docker build -t $ECR_REPOSITORY:$IMAGE_TAG .
          docker tag $ECR_REPOSITORY:$IMAGE_TAG $IMAGE_URI
          docker push $IMAGE_URI
          echo "IMAGE_URI=$IMAGE_URI" >> $GITHUB_ENV

      # 7. Task Definition을 새로운 이미지로 업데이트
      - name: Update Task Definition with new image
        env:
          AWS_REGION: ap-northeast-2
          IMAGE_URI: ${{ steps.login-ecr.outputs.registry }}/aendyear-back:latest
        run: |
               echo "Task Definition 업데이트 시작..."
          # 기존 Task Definition 가져오기
               TASK_FAMILY=$(aws ecs describe-task-definition --task-definition AendyearTask --query 'taskDefinition.family' --output text --region $AWS_REGION)
          
          # 새로운 이미지로 Task Definition 업데이트
               NEW_TASK_DEF=$(aws ecs register-task-definition \
               --family $TASK_FAMILY \
               --container-definitions '[{"name":"komawotsir-container","image":"'$IMAGE_URI'","essential":true,"portMappings":[{"containerPort":8080,"hostPort":8080}]}]' \
               --query 'taskDefinition.taskDefinitionArn' \
               --output text \
               --region $AWS_REGION)
               
               echo "새로운 Task Definition ARN: $NEW_TASK_DEF"

          # 환경 변수에 새 Task Definition ARN 저장
               echo "NEW_TASK_DEF=$NEW_TASK_DEF" >> $GITHUB_ENV

      # 8. ECS 서비스 업데이트
      - name: Update ECS Service with new Task Definition
        env:
          AWS_REGION: ap-northeast-2
          CLUSTER_NAME: AendyearCluster
          SERVICE_NAME: komawotsir-aendyear
        run: |
          echo "ECS 서비스 업데이트 시작..."
          aws ecs update-service \
            --cluster $CLUSTER_NAME \
            --service $SERVICE_NAME \
            --task-definition $NEW_TASK_DEF \
            --region $AWS_REGION

          echo "ECS 서비스 안정화 대기 중..."
          aws ecs wait services-stable \
            --cluster $CLUSTER_NAME \
            --services $SERVICE_NAME \
            --region $AWS_REGION || { echo "ECS 서비스 안정화 실패"; exit 1; }
          echo "ECS 서비스 업데이트 완료."