name: Deploy to ECS

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      # 1. Checkout Repository
      - name: Checkout code
        uses: actions/checkout@v2

      # 2. Set AWS Credentials
      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v2
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ap-northeast-2

      # 3. Log in to Amazon ECR
      - name: Log in to Amazon ECR
        uses: aws-actions/amazon-ecr-login@v1

      # 4. Build and Push Docker Image
      - name: Build and Push Docker Image
        run: |
          ECR_REPO_NAME="aendyear-front"
          IMAGE_TAG="latest"
          REPOSITORY_URI="${{ secrets.AWS_ACCOUNT_ID }}.dkr.ecr.ap-northeast-2.amazonaws.com/$ECR_REPO_NAME"

          # Build Docker image
          docker build -t $ECR_REPO_NAME:$IMAGE_TAG .

          # Tag the image for ECR
          docker tag $ECR_REPO_NAME:$IMAGE_TAG $REPOSITORY_URI:$IMAGE_TAG

          # Push the image to ECR
          docker push $REPOSITORY_URI:$IMAGE_TAG

      # 5. Update Task Definition and Deploy to ECS
      - name: Update Task Definition and Deploy to ECS
        run: |
          ECR_REPO_NAME="aendyear-front"
          IMAGE_TAG="latest"
          REPOSITORY_URI="${{ secrets.AWS_ACCOUNT_ID }}.dkr.ecr.ap-northeast-2.amazonaws.com/$ECR_REPO_NAME"

          # Fetch existing Task Definition
          aws ecs describe-task-definition \
            --task-definition AendyearTask \
            --region ap-northeast-2 > aendyear-task-definition.json

          # Update Task Definition with the new image
          jq '.taskDefinition.containerDefinitions[0].image = "'$REPOSITORY_URI:$IMAGE_TAG'"' aendyear-task-definition.json \
            | jq 'del(.taskDefinitionArn, .revision, .status, .requiresAttributes, .compatibilities, .registeredBy, .registeredAt)' \
            > new-task-definition.json

          # Register the updated Task Definition
          aws ecs register-task-definition \
            --cli-input-json file://new-task-definition.json \
            --region ap-northeast-2

          # Update ECS Service
          aws ecs update-service \
            --cluster AendyearCluster \
            --service komawotsir-front \
            --task-definition AendyearTask \
            --force-new-deployment \
            --region ap-northeast-2
